### ISSUE TITLE
keyboard not showing characters

### ISSUE THREAD

**Issue by lavvy** [wdullaer/xbmc_nbox_skin#3]
hello, i just noticed that the keyboard is not working  in the helix version.

**Comment by wdullaer** [comment]
Hey there,
I've tweaked this one to be compatible with gotham.
The theme spec has been updated again for Helix, but I currently don't have a build of Helix running, so I haven't updated this yet.

In short: it's to be expected that there are issues when running this in Helix, but I'm happy to merge in pull requests if you manage to fix some of them.

**Comment by lavvy** [comment]
I may not be a good user and coder cos I just copied the folder to the addons folder of xbmc. 
But I am always testing nbox cos that's my preferred skin.
I noticed that your Gotham fork works well with helix. Only issue is the virtual keyboard. in helix kodi used more keyboard formats.

**Comment by lavvy** [comment]
Is there any success

**Comment by wdullaer** [comment]
Helix changed the keyboard layout, so I'll need to do some changes.
I'm very busy this week, so I'm not sure I'll be able to take a look at this very soon, but I'll eventually get around to it.

**Comment by wdullaer** [comment]
@lavvy you can checkout the helix branch for a Helix compatible version.
The keyboard shows up and I've cleaned up the subtitle dialog.
The PVR bit is horribly broken and it will currently not install by zipping it up. You'll have to add it to the addons folder yourself.

I intend to make it install from the zip, the PVR screens I probably won't fix (no PVR and frankly, no interest)

**Comment by lavvy** [comment]
thumbs up @wdullaer  .  please if i want to make nbox my default xbmc skin before compiling , how do i do it. i have tried renaming it to skin.confluence. it worked but it could not load the background image.  it looks to me the background image does not really correspond .

**Comment by wdullaer** [comment]
I don't compile xbmc from source, so I'm not sure if I'm the right person to ask.

What I'd try to do is see if you can stream in the nbox addon when building your image, along with a guisettings.xml that has nbox selected as the skin you want to use.

**Comment by lavvy** [comment]
@wdullaer looks like this issue has reappeared in the latest version ver. 1.2.1.  The key characters are not showing up. It seems somehow the color of the characters are the same with the background color . Please take a look
